### ISSUE TITLE
Nakijken

### ISSUE THREAD

**Issue by jwittenberg** [hanaim-devops/devops-blog-jwittenberg#1]

**Comment by bartvanderwal** [comment]
Hoi Joris,

Ik had al beoordeling gepushed in je repo. Maar heb nu ook iSAS formulier ingevuld. Helaas nog niet voldoende, o.a. vanwege geheel missen van de (verplichte) illustraties.

Graag dit issue re-openen na reparatie/herkansing. je kan bronnen erbij zoeken, plaatje maken, leeswijzer toevoegen en even kijken naar structuur, en wat (te) korte kopjes. Sommige weinig concrete stukken kun je wellicht ook juist schrappen, en. bv. meer use case van 'code coverage' uitwerken voor hands-on, en ook casus voor PitStop of hello world applicatie.

Want je hebt al wel ca. 1500 woorden zag ik (telde VS code) en dit moet 800- max 1500) zijn.
